-- 코드를 입력하세요
SELECT ANIMAL_TYPE, COUNT(*) AS count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY 
    CASE
        WHEN ANIMAL_TYPE = 'CAT' THEN 1
        WHEN ANIMAL_TYPE = 'DOG' THEN 2
    END,
    NAME ASC;
